Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Fahrenheit
// Autor(a)    : Lara dos Santos Dourado
// Data atual  : 05/12/2024
Var
// Seção de Declarações das variáveis 
F,C: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite a temperatura em Fahrenheit: ")
Leia(F)
C <- (F - 32) * 5 / 9

Escreval("A temperatura em Celsius é: ", C:0:2)


Fimalgoritmo